### ISSUE TITLE
equal height on resize

### ISSUE THREAD

**Issue by Guthix2827** [status201/jquery-equalheights#2]
Hey,
I having issue with height on resize, it doesn't calculating the height on resize.
only on document ready.. I even tried wrap it on resize function to initlize it but it
doesn't works.

**Comment by status201** [comment]
Hi,

That's strange. onResize is an option which is true by default. So it should resize.
https://codepen.io/status201/pen/xwXEOm

My guess would be a conflicting script (returning false on resize?).
Do you have a live example somewhere?

**Comment by Guthix2827** [comment]
Hey, thanks for fast commenting.
here's the url: ***
the object that I want to be equal size is the main slider under the nav menu.
the image on the left and the content block on the right, when resize it doesn't really resize them.
I'm using slick slide for this block because it's gonna be carousel at the end.

**Comment by Guthix2827** [comment]
I have used it on other blocks and it doesn't update on resize also..

**Comment by Guthix2827** [comment]
any updates?

**Comment by status201** [comment]
It's hard for me to debug your site, Hebrew doesn't help me ;-)

My advice is to test with your own onresize event handler and see how that works. You should disable the equalHeights resize handler with the appr. option.

```
$( window ).resize(function() {
    $('.blocks').equalHeights({
        onResize: false
    });
});
```
For scaling a slider/slideshow, best thing would be to use a hook to manually trigger equalHeights().

Good luck!
