### ISSUE TITLE
The minified version is ahead of the uncompressed version

### ISSUE THREAD

**Issue by leigh-ols** [status201/jquery-equalheights#3]
The latest commit only updated the minified version and not the full/dev version.

Also the npm package needs updating `npm i jquery-equalheights` installs v1.0.3, which is buggy.

**Comment by status201** [comment]
I updated the version number (code was the same).
Will look into npm, sorry for the inconvenience.

**Comment by status201** [comment]
Updated to v1.0.6. Published to NPM.
Everything should be up to date now.
https://www.npmjs.com/package/jquery-equalheights
